version: '3.9'

x-common:
  &common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./logs:/app/logs
    - .env:/.env
  environment:
    &common-env
    TZ: "Asia/Shanghai"

services:
  search_server:
    <<: *common
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0","--port", "8004" ]
    ports:
      - "8004:8004"
    restart: always
    environment:
      <<: *common-env
  